---
name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          version: "0.11.13"

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: 
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.13"
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: uv run --frozen pytest
